### ISSUE TITLE
Clarification of example @context

### ISSUE THREAD

**Issue by robdefeo** [w3c/vc-data-model-2.0-test-suite#71]
From the readme, there is this section.

> Implementations are expected to not error when any of the following context
> files are used in a verifiable credential or a verifiable presentation:
> 
> - [VC 2.0 Context - https://www.w3.org/ns/credentials/v2](https://www.w3.org/ns/credentials/v2)
> - [VC Examples Context - https://www.w3.org/ns/credentials/examples/v2](https://www.w3.org/ns/credentials/examples/v2)

However based on the test cases this is inconsistent, e.g. https://github.com/w3c/vc-data-model-2.0-test-suite/blob/main/tests/input/credential-type-unmapped-fail.json is 

```
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "type": [
    "VerifiableCredential",
    "ExampleTestCredential"
  ],
  "issuer": "did:example:issuer",
  "credentialSubject": {
    "id": "did:example:subject"
  }
}
```

Since it contains `https://www.w3.org/ns/credentials/v2` the statement 

> Implementations are expected to not error when any of the following context files are used in a verifiable credential or a verifiable presentation:

This statement is incorrect based on the word `any`. What is the correct statement/implementation:

- `any` should be replaced with `both`
- or `https://www.w3.org/ns/credentials/v2` should be removed from the list

**Comment by BigBlueHat** [comment]
@robdefeo I think the current spec text is more clarifying: https://w3c.github.io/vc-data-model/#dfn-context
> The value of the @context [property](https://w3c.github.io/vc-data-model/#dfn-property) MUST be an [ordered set](https://infra.spec.whatwg.org/#ordered-set) where the first item is a [URL](https://w3c.github.io/vc-data-model/#dfn-url) with the value https://www.w3.org/ns/credentials/v2.

That said, it does look like that test fixture had been incorrect. Things in the test suite have moved forward since then as well and that test file now contains content that should cause a failure.

Thanks for reporting the bug! Please keep them coming! 😃

**Comment by BigBlueHat** [comment]
Ah, also, it looks like  https://github.com/w3c/vc-data-model-2.0-test-suite/blob/main/tests/input/credential-type-unmapped-fail.json was specifically for testing _unmapped types_ and has a value in the `type` field that was not listed in the context.

The updated fixture now further prevents confusion by clearing out the `@vocab` value--which is likely being removed from the VCDMv2 context since it continues to cause confusion.

**Comment by robdefeo** [comment]
Thanks @BigBlueHat this helps a lot
